### ISSUE TITLE
error  Unexpected token <

### ISSUE THREAD

**Issue by peponi** [BenoitZugmeyer/eslint-plugin-html#2]
Hello

and thx for you plugin
I have tried to use it but I got this error

```
/home/peponi/Code/private_projects/FirefoxOS/Wallet_WebApp/app/index.html
  1:1  error  Unexpected token <
```
seems the *htmlparser2* won't work or so

may be you can tell me what I'm doing wrong

here is my [gulp task](https://github.com/peponi/Wallet_WebApp/blob/test/eslint/Gulpfile.js)
```
gulp.task('eslint', function () {
    return gulp.src(['app/js/**/*.js','app/index.html'])
        .pipe(eslint({
            plugins: ["html"]
        }))
        .pipe(eslint.format())
        .pipe(eslint.failOnError());
});
```
[.eslintrc](https://github.com/peponi/Wallet_WebApp/blob/test/eslint/.eslintrc)
```
...
  vm: true
  xtag: true
  ViewModel: true
plugins: 
  - html
rules: 
  block-scoped-var: true
  camelcase: true
...
```

and [package.json](https://github.com/peponi/Wallet_WebApp/blob/test/eslint/package.json)
```
  "devDependencies": {
    "eslint-plugin-html": "^1.0.0",
    "gulp": "^3.8.11",
    "gulp-eslint": "^0.9.0"
  },
```
